
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: whitelist-intra-cluster-out
spec:
  selector: tigera.io/type == "master"
  order: 20
  types:
  - Egress
  egress:
  - action: Allow

    
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: whitelist-intra-cluster-in
spec:
  selector: tigera.io/type == "master"
  order: 20
  types:
  - Ingress
  ingress:
  - action: Allow

